name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        default: 'main'
      torch_minor:
        description: PyTorch minor version
        required: true
        type: number
        default: '8'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: number
        default: '0'
      torch_is_nightly:
        description: PyTorch is nightly
        type: boolean
#      cuda_major:
#        description: CUDA major version
#        required: true
#        type: number
#        default: '12'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: number
        default: '9'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: number
        default: '1'
      extra_cuda_arch:
        description: Extra CUDA arch
      extra_wheel_version_suffix:
        description: Extra wheel version suffix
      is_python_abi3:
        description: Is Python ABI3
        type: boolean

jobs:
  build-sageattn:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      # Jimver/cuda-toolkit @>=0.0.24 is broken on Windows:
      # https://github.com/Jimver/cuda-toolkit/issues/395#issuecomment-3237240046
      - uses: N-Storm/cuda-toolkit@master
        with:
          cuda: 12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false
          use-local-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel
        env:
          #CUDA_MAJOR_VERSION: ${{ inputs.cuda_major }}
          CUDA_MINOR_VERSION: ${{ inputs.cuda_minor }}
          TORCH_MINOR_VERSION: ${{ inputs.torch_minor }}
          TORCH_PATCH_VERSION: ${{ inputs.torch_patch }}
          DISTUTILS_USE_SDK: 1
          SAGEATTENTION_WHEEL_VERSION_SUFFIX: +cu12${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}${{ inputs.extra_wheel_version_suffix }}
          CIBW_BUILD: "{cp39-win_amd64"
          CIBW_BUILD_VERBOSITY: 1
          TORCH_CUDA_ARCH_LIST: "8.0 8.6 8.9 9.0"
          #CIBW_DEPENDENCY_VERSIONS: latest
        run: |
          # Get-ChildItem Env:
          # (Get-WmiObject Win32_Processor).Name
          # (Get-WmiObject Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum / 1GB
          # (Get-WmiObject Win32_VideoController).Name

          # Get-Command -All python
          # python --version
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          if ($${{ inputs.torch_is_nightly }})
          {
            $Env:TORCH_IS_NIGHTLY = "1"
          }
          python update_pyproject.py

          Start-Process -NoNewWindow simpleindex simpleindex.toml
          $Env:PIP_INDEX_URL = "http://127.0.0.1:8000"

          if ($Env:CUDA_MINOR_VERSION -gt 6)
          {
            $Env:TORCH_CUDA_ARCH_LIST += " 12.0"
          }
          if ("${{ inputs.extra_cuda_arch }}")
          {
            $Env:TORCH_CUDA_ARCH_LIST += " ${{ inputs.extra_cuda_arch }}"
          }
          if (!$${{ inputs.is_python_abi3 }}) {
            $Env:CIBW_BUILD += ",cp310-win_amd64,cp311-win_amd64,cp312-win_amd64"
            if ($Env:TORCH_MINOR_VERSION -gt 5)
            {
              $Env:CIBW_BUILD += ",cp313-win_amd64"
            }
          }
          $Env:CIBW_BUILD += "}"
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
          if-no-files-found: error
